apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends-deployment
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  strategy: {}
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: techtrends
        ports:
          - containerPort: {{ .Values.containerPort }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.containerPort }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.containerPort }}
        resources:
{{ toYaml .Values.resources | indent 12}}